Add current SETS_2 Code and moved old code to folder
ISSUIUC/Solid_Propulsion pull request #37
Opened 2024-09-24 01:42 UTC by MylesLJ

2024-09-24 01:52 UTC, mariano-f-r requested changes
Looks good except for a few extraneous things we need to clean up. Nanny duty :)

2024-09-24 01:52 UTC, mariano-f-r commented on Test Stand/Sets_2/.DS_Store
We can delete .DS_Store files as they are intrinsic to MacOS only

2024-09-24 01:52 UTC, mariano-f-r commented on Test Stand/Sets_2/SETS_2 Code/.DS_Store
See above

2024-09-24 01:52 UTC, mariano-f-r commented on Test Stand/Sets_2/SETS_2 Code/Old_Code/New Press Dat_Test.py
We should avoid having spaces in file names

2024-10-01 00:58 UTC, MylesLJ reviewed
Deleted .DS_Store files. Lgtm

2024-10-01 00:59 UTC, mariano-f-r approved these changes

2024-10-01 00:59 UTC, merged